---

- name: Install non-default packages
  pacman: name=vim,rsync,htop,bash-completion,imagemagick,ntp,ffmpeg,sox state=present

- name: Update root dirs
  synchronize: src=FBRoot/ dest=/ archive=no recursive=yes links=yes

- name: Ensure folder permissions are good
  raw: chmod 700 /root /root/.ssh
- name: Ensure auth_keys permissions are good
  raw: chmod 600 /root/.ssh/authorized_keys
- name: Ensure binaries permissions are good
  raw: chmod +rx /usr/local/bin/*

- name: Enable NTP
  raw: systemctl enable ntpd && systemctl start ntpd


