[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FOSDEM Audio Control CLI"
version = "0.0.1"

dependencies = [
    "click",
    "click-shell",
    "tabulate",
    "pyserial",
    "python-osc",
    "auto-click-auto",
]